### PR TITLE
ronaldpasipanodyaBEAssessment

### PR DESCRIPTION
**Pull request by ronaldpasipanodya**
had issues with my internet connectivity hence the three commits  but the commit "first commit(Ronald Pasipanodya )" contains the whole project and the database scripts.

### CODE REVIEW

**Comment by pieter-iplatform** [comment]
Morning,

Thank you for your submission.

The /artist/<artist_id>/releases is not returning the requested data in the format described in the assessment. It seems to try and conver the MusicBrainz XML into JSON and just return the JSON

image

Can you please update the assessment to return the information requested in the assessment?

Thanks
Pieter

**Comment by BallinGit** [comment]
Hi Pieter,

Sure no problem.
I will get right on it asap.
Its actually returning the whole release as a Task<ReleaseMetadata>
I think the Task.Result should be a object.
but yes i can exclude the items you do not need.

I just have a few high priority tasks right now.
but will get on it asap

Again thank you for the opportunity.
this was a really nice assessment. i like the challenge.

**Comment by ronaldpasipanodya** [comment]
thanks for the feedback. please check the new commit

**Comment by pieter-iplatform** [comment]
Thank you for completing the assessment.

Your agent will be in touch with you.

Pieter

**Pull request closed without merging**
