### PR TITLE
Submitt for Review

### PR DESCRIPTION
**Pull request by G00gle786**

### CODE REVIEW

**Comment by pieter-iplatform** [comment]
Thank you.

We will look at the assessment tomorrow (16/10) and give feedback.

Thanks
Pieter

**Comment by pieter-iplatform** [comment]
Hi,

The solution does not compile. I have updated the nugets. It seems there are hardcoded paths in the solution file point to your file system.

Thanks
Pieter

**Comment by G00gle786** [comment]
Hi there pieter -

Let me have a look and will revert back to you ...

Re
Yaseen

**Comment by G00gle786** [comment]
Hi there Pieter,
How are you doing - I tried submitting yesterday as well as this morning
and getting the following error - were there any permission changes on the
repository?

[image: Inline image 1]

I'm trying to submit from work which was successful the last time - if I
don't come right here at work, will try to submit from home and let you
know ..

Re
Yaseen

On Wed, Oct 21, 2015 at 12:49 PM, Yaseen Suleman <yaseen.i.suleman@gmail.com

> wrote:
> 
> Hi there pieter -
> 
> Let me have a look and will revert back to you ...
> 
> Re
> Yaseen
> 
> On Wed, Oct 21, 2015 at 6:52 AM, pieter-iplatform <

**Comment by pieter-iplatform** [comment]
Hi Yaseen,

We have not made any changes to the repo. I'll close this pull request. Can you then try and send another pull request?

Thanks
Pieter

**Pull request closed without merging**
