### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ghost**
Backend Developer Assessment (B. Smith)

### CODE REVIEW

**Comment by pieter-iplatform** [comment]
Hi,

I have pulled your version, but on compilation of the solution I get the following errors

Severity    Code    Description Project File    Line
Error   CS0103  The name 'Assert' does not exist in the current context Assessment.NUnitTests   C:\Data\development\interviews\sequ3l\Assessment.NUnitTests\ArtistTest.cs   37
Severity    Code    Description Project File    Line
Error   CS0103  The name 'Is' does not exist in the current context Assessment.NUnitTests   C:\Data\development\interviews\sequ3l\Assessment.NUnitTests\ArtistTest.cs   28
Severity    Code    Description Project File    Line
Error   CS0246  The type or namespace name 'MBReleaseInfoDTO' could not be found (are you missing a using directive or an assembly reference?)  Assessment.BusinessLogic    C:\Data\development\interviews\sequ3l\Assessment.BusinessLogic\ThirdParty\MusicBrainz.cs    78
Severity    Code    Description Project File    Line
Error   CS0246  The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?) Assessment.NUnitTests   C:\Data\development\interviews\sequ3l\Assessment.NUnitTests\ArtistTest.cs   8
Severity    Code    Description Project File    Line
Error   CS0246  The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)  Assessment.NUnitTests   C:\Data\development\interviews\sequ3l\Assessment.NUnitTests\ArtistTest.cs   21
Severity    Code    Description Project File    Line
Error   CS0246  The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)   Assessment.NUnitTests   C:\Data\development\interviews\sequ3l\Assessment.NUnitTests\ArtistTest.cs   18

image

Thanks
Pieter

**Comment by ghost** [comment]
Hello Pieter,

Thank you for getting back to me. By default git's ignore file excludes the
packages folder created with the project. I usually add any custom
libraries directly to packages if it's not added via NuGet. In this case
it's the assembly for NUnit tests. I added it via NuGet so you should be
able to restore it, I did however manually commit the files in question
too. Let me know if there's anything else I can help with!

Kind regards,
Ben

**Comment by pieter-iplatform** [comment]
Hi,

I restored all the nugets, but it seems the nunit.framework reference is missing (both from the packages folder or hard coded libs).

image

The MBReleaseInfoDTO is also missing.

Thanks
Pieter

**Comment by ghost** [comment]
Hello Pieter,

I've commited some changes I made to the project structure (specifically
renaming the folder for MusicBrainz models in the Assessment.Models
project). This should solve the issue of MBReleaseInforDTO.cs being missing
as it got excluded thanks to .gitignore that excludes anything with
"release" as a name I believe. I also ignored the entire packages folder
and made small changes that should help resolve the issue of not finding
the nunit.framework assembly if you run a restore on the Assembly.NUnit
project packages.

Kind regards,
Ben

**Pull request closed without merging**
